# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provision :shell, :inline => "apt-get update"

  config.vm.box = "ubuntu/xenial64"
  #config.vm.box = "ubuntu/trusty64" # na tym jest puppet

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provision "shell", path: "puppet.sh"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file  = "default.pp"
  end

end
